spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fooddb
    username: root
    password: "{cipher}05d2c7f62ed1d2b1acce6a284eeb34d386cb62e6428f5025fae9e3479bdcf933"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: "Food Service"
    description: "Food service microservice"
    version: "1.0"
