
# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=user
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ===============================
# Actuator Info
# ===============================
management.info.env.enabled=true

info.app.name=Restaurant Service
info.app.description=Restaurant Service - Development Environment
info.app.version=1.0.0-DEV
info.app.environment=Development
info.app.author=Irfan