
# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=user
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Restaurant Service
info.app.description=Restaurant Service - Production Environment
info.app.version=1.0.0
info.app.environment=Production
info.app.author=Irfan



